version: '3.8'

services:
  bot:
    build: .
    container_name: vgltu_bot
    restart: unless-stopped
    volumes:
      - bot_data:/data
    env_file:
      - .env
    environment:
      - DATA_DIR=/data
      - TZ=Europe/Moscow

volumes:
  bot_data:
